import os
import time
import logging
import argparse
import subprocess

from jinja2 import Environment, FileSystemLoader

def write_ldmx_config(cwd, config_tpl, n_events, seed, mass, decay_length):
    # Define generated python config file name
    py_config_file = '%sGeV_seed%i_gamma_decay%s.py' % (str(mass), seed, str(decay_length)) 

    # Define ROOT file name generated by LDMX
    result_root_file = 'AlpToe+e-_%sGeV_seed%i_gamma_decay%s.root' % (str(mass), seed, str(decay_length)) 

    # Auto-locate absolute paths for LHE files from the previous step
    prod_lhe_file = '%s/ALP_LHE_Directory/gamma_decay%s/%sGeV/AlpToe+e-_%sGeV_seed%i_gamma_prod.lhe' % (cwd, str(decay_length), str(mass), str(mass), seed) 
    decay_lhe_file = '%s/ALP_LHE_Directory/gamma_decay%s/%sGeV/AlpToe+e-_%sGeV_seed%i_gamma_decay.lhe' % (cwd, str(decay_length), str(mass), str(mass), seed) 

    # Load jinja2 template
    fileLoader = FileSystemLoader(cwd)
    env = Environment(loader = fileLoader)
    template = env.get_template(config_tpl)

    # Write LDMX config file
    logging.info('Writing LDMX configuration file.')
    with open(py_config_file, 'w') as file:
        file.write(template.render(
            root_file = result_root_file,
            n_events = n_events,
            seed = seed,
            prod_file = prod_lhe_file,
            decay_file = decay_lhe_file
        ))

    return py_config_file, result_root_file

def main():
    # Parse command line arguments
    parser = argparse.ArgumentParser(description = 'ALP ldmx Config Generator')

    parser.add_argument('--config_tpl',   type = str,                   help = 'Name of ldmx config file template (needs to be in working directory).')
    # Default to 20000 to match previous step if --n_events is omitted
    parser.add_argument('--n_events',     type = int,   default=20000,  help = 'Number of events to generate.')
    parser.add_argument('--seed',         type = int,                   help = 'Random seed.')
    parser.add_argument('--decay_length', type = int,                   help = 'Lab frame decay length.')
    parser.add_argument('-t', action = 'store_true', dest = 'test',     help = 'Run the job locally instead of submitting it to the batch.')

    args = parser.parse_args()

    # Configure logging output
    logging.basicConfig(format = '[ Production ][ %(levelname)s ]: %(message)s', level = logging.DEBUG)

    cwd = os.getcwd()
    config_tpl_path = cwd + '/' + args.config_tpl

    if not os.path.exists(config_tpl_path): 
        parser.error(f'Config template file not found: {config_tpl_path}')

    # Create output directory structure
    output_dir = cwd + '/ALP_LDMX_Directory/gamma_decay%s' % str(args.decay_length)
    if not os.path.exists(output_dir):
        logging.info('Output directory does not exist and now will be created.')
        os.makedirs(output_dir)

    log_out = output_dir + '/log_output' 
    if not os.path.exists(log_out):
        os.makedirs(log_out)

    ldmx_config_out = output_dir + '/config_output' 
    if not os.path.exists(ldmx_config_out):
        os.makedirs(ldmx_config_out)

    job_script_out = output_dir + '/job_script_output' 
    if not os.path.exists(job_script_out):
        os.makedirs(job_script_out)

    ALP_mass_list = [0.005, 0.025, 0.05, 0.5, 1.0]

    for mass in ALP_mass_list:
        logging.info('Generating LDMX config file for mass %s GeV.' % str(mass))

        mass_dir = output_dir + '/%sGeV' % str(mass) 
        if not os.path.exists(mass_dir):
            os.makedirs(mass_dir)

        # Write specific py config file
        config_file, output_root_file = write_ldmx_config(cwd, args.config_tpl, args.n_events, args.seed, mass, args.decay_length)

        # Move config file to dedicated folder
        logging.info('Copying config file %s to %s' % (config_file, ldmx_config_out) )
        os.system('mv %s %s' % (config_file, ldmx_config_out))

        # Generate Slurm job script
        logging.info('Generating job script for mass %s GeV' % str(mass))
        with open('%s/sbatch_%sGeV_seed%i_gamma_ldmx.sh' % (job_script_out, str(mass), args.seed), 'w') as f:
            f.write('#!/bin/bash\n\n')
            f.write('#SBATCH --job-name=%sGeV_seed%i_gamma_ldmx\n' % (str(mass), args.seed))
            f.write('#SBATCH --nodes=1 --ntasks-per-node=1\n')
            f.write('#SBATCH --ntasks-per-node=1\n')
            f.write('#SBATCH -o %s/%sGeV_seed%i_gamma_ldmx.out\n' % (log_out, str(mass), args.seed))
            f.write('#SBATCH --mail-type=all\n')
            # Uncomment and edit email below to receive notifications
            # f.write('#SBATCH --mail-user=your_email@ucsb.edu\n')
            f.write('#SBATCH -t 12:00:00\n')
            f.write('#SBATCH -D %s\n\n' % cwd)

            # Setup Apptainer and Denv environment for the cluster
            f.write('module load apptainer\n')
            f.write('export APPTAINER_USERNS=1\n')
            
            # Run LDMX script using denv fire
            f.write('denv fire %s\n' % (ldmx_config_out + '/' + config_file))
            
            # Move generated root file to target mass directory upon completion
            f.write('mv %s %s\n' % (output_root_file, mass_dir))

        # Submit job
        submit_command = 'sbatch %s/sbatch_%sGeV_seed%i_gamma_ldmx.sh' % (job_script_out, str(mass), args.seed)
        logging.info('Job submit command: %s\n' % submit_command)

        if not args.test: 
            subprocess.Popen(submit_command, shell=True).communicate()
            time.sleep(3)

if __name__ == '__main__':
    main()